version: '3'
services:
  zookeeper:
    image: zookeeper:latest
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zookeeper:2888:3888;2181
    volumes:
      - ./pinot-docker-demo/zookeeper/data:/data
      - ./pinot-docker-demo/zookeeper/datalog:/datalog

  pinot-controller:
    image: apachepinot/pinot:release-0.7.1
    hostname: pinot-controller
    volumes:
      - ./pinot-docker-demo/pinot/controller:/tmp/data/controller
    ports:
      - "9000:9000"
    command: StartController -zkAddress zookeeper:2181

  pinot-broker:
    image: apachepinot/pinot:release-0.7.1
    hostname: pinot-broker
    ports:
      - "8099:8099"
    command: StartBroker -zkAddress zookeeper:2181
    depends_on:
      - zookeeper
      - pinot-controller
      
  pinot-server:
    image: apachepinot/pinot:release-0.7.1
    hostname: pinot-server
    volumes:
      - ./pinot-docker-demo/pinot/server:/tmp/data/server
    ports:
      - "8098:8098"
    command: StartServer -zkAddress zookeeper:2181
    depends_on:
      - zookeeper
      - pinot-controller




